### ISSUE TITLE
(JP) group by 付きの集約関数実行(EXPLAIN)でAssertion Failed

### ISSUE THREAD

**Issue by onlyindreams** [pg-strom/devel#106]
最新のcustom_joinブランチで発生しています。
ENABLED_CASSERT”なし”だとエラーなく正常に処理が返されます。

再現クエリ
```
set pg_strom.debug_force_gpupreagg to on;
drop table if exists orz;
create table orz as select 1 as key,1 as value;
explain select key,count(value) from orz group by key;
```

エラーメッセージ
```
contrib_regression=# explain select key,count(value) from orz group by key;
TRAP: FailedAssertion("!(var->varno == varno)", File: "execScan.c", Line: 291)
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: 2015-01-09 18:23:42 JST DB: PID:19887 LOG:  00000: server process (PID 19926) was terminated by signal 6: Aborted
```

--enable-cassertなしのときのEXPLAIN ANALYZE
```
contrib_regression=# explain analyze verbose select key,count(value) from orz group by key;
                                                             QUERY PLAN                                                             
------------------------------------------------------------------------------------------------------------------------------------
 HashAggregate  (cost=1011.06..1013.06 rows=200 width=8) (actual time=0.816..0.817 rows=1 loops=1)
   Output: key, sum((pgstrom.nrows((value IS NOT NULL))))
   Group Key: orz.key
   ->  Custom Scan (GpuPreAgg)  (cost=1000.00..1010.06 rows=200 width=12) (actual time=0.801..0.805 rows=1 loops=1)
         Output: key, NULL::integer, pgstrom.nrows((value IS NOT NULL))
         Bulkload: On
         ->  Custom Scan (GpuScan) on public.orz  (cost=500.00..510.00 rows=2140 width=8) (actual time=0.020..0.027 rows=1 loops=1)
               Output: key, value
 Planning time: 0.151 ms
 Execution time: 0.896 ms
(10 rows)
```

バックトレース
```
Program terminated with signal 6, Aborted.
#0  0x0000003cdbc32925 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.132.el6.x86_64 libgcc-4.4.7-4.el6.x86_64 libstdc++-4.4.7-4.el6.x86_64 numactl-2.0.7-8.el6.x86_64
(gdb) bt
#0  0x0000003cdbc32925 in raise () from /lib64/libc.so.6
#1  0x0000003cdbc34105 in abort () from /lib64/libc.so.6
#2  0x00000000008e3192 in ExceptionalCondition (conditionName=0xa5ca80 "!(var->varno == varno)", errorType=0xa5ca53 "FailedAssertion", fileName=0xa5ca48 "execScan.c", lineNumber=291)
    at assert.c:54
#3  0x0000000000651939 in tlist_matches_tupdesc (ps=0x19e69d0, tlist=0x19db648, varno=65002, tupdesc=0x19e78f8) at execScan.c:291
#4  0x0000000000651843 in ExecAssignScanProjectionInfo (node=0x19e69d0) at execScan.c:261
#5  0x000000000065d9ef in ExecInitCustomScan (cscan=0x19dbeb0, estate=0x19e5fb8, eflags=17) at nodeCustom.c:83
#6  0x0000000000646049 in ExecInitNode (node=0x19dbeb0, estate=0x19e5fb8, eflags=17) at execProcnode.c:249
#7  0x000000000065a3f4 in ExecInitAgg (node=0x19daaa8, estate=0x19e5fb8, eflags=17) at nodeAgg.c:1576
#8  0x0000000000646122 in ExecInitNode (node=0x19daaa8, estate=0x19e5fb8, eflags=17) at execProcnode.c:290
#9  0x000000000064304c in InitPlan (queryDesc=0x19e2480, eflags=17) at execMain.c:892
#10 0x00000000006420ba in standard_ExecutorStart (queryDesc=0x19e2480, eflags=17) at execMain.c:208
#11 0x0000000000641ebe in ExecutorStart (queryDesc=0x19e2480, eflags=1) at execMain.c:122
#12 0x00000000005dc913 in ExplainOnePlan (plannedstmt=0x19db0c8, into=0x0, es=0x7fffe5e3e1f0, queryString=0x198a048 "explain select key,count(value) from orz group by key;", params=0x0, 
    planduration=0x7fffe5e3e160) at explain.c:472
#13 0x00000000005dc636 in ExplainOneQuery (query=0x1946800, into=0x0, es=0x7fffe5e3e1f0, queryString=0x198a048 "explain select key,count(value) from orz group by key;", params=0x0)
    at explain.c:340
#14 0x00000000005dc2a9 in ExplainQuery (stmt=0x198b1e8, queryString=0x198a048 "explain select key,count(value) from orz group by key;", params=0x0, dest=0x193b7d8) at explain.c:231
#15 0x00000000007b4057 in standard_ProcessUtility (parsetree=0x198b1e8, queryString=0x198a048 "explain select key,count(value) from orz group by key;", context=PROCESS_UTILITY_TOPLEVEL, 
    params=0x0, dest=0x193b7d8, completionTag=0x7fffe5e3e450 "") at utility.c:648
#16 0x00000000007b3796 in ProcessUtility (parsetree=0x198b1e8, queryString=0x198a048 "explain select key,count(value) from orz group by key;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, 
    dest=0x193b7d8, completionTag=0x7fffe5e3e450 "") at utility.c:313
#17 0x00000000007b287e in PortalRunUtility (portal=0x1938458, utilityStmt=0x198b1e8, isTopLevel=1 '\001', dest=0x193b7d8, completionTag=0x7fffe5e3e450 "") at pquery.c:1187
#18 0x00000000007b25cd in FillPortalStore (portal=0x1938458, isTopLevel=1 '\001') at pquery.c:1061
#19 0x00000000007b1ede in PortalRun (portal=0x1938458, count=9223372036854775807, isTopLevel=1 '\001', dest=0x198b920, altdest=0x198b920, completionTag=0x7fffe5e3e630 "") at pquery.c:785
#20 0x00000000007abfe7 in exec_simple_query (query_string=0x198a048 "explain select key,count(value) from orz group by key;") at postgres.c:1045
#21 0x00000000007b01bb in PostgresMain (argc=1, argv=0x191f128, dbname=0x191ef78 "contrib_regression", username=0x191ef58 "nanzai") at postgres.c:4012
#22 0x00000000007352a3 in BackendRun (port=0x1947ba0) at postmaster.c:4130
#23 0x00000000007349d8 in BackendStartup (port=0x1947ba0) at postmaster.c:3805
#24 0x000000000073119a in ServerLoop () at postmaster.c:1573
#25 0x00000000007308a3 in PostmasterMain (argc=1, argv=0x191df20) at postmaster.c:1220
#26 0x0000000000690997 in main (argc=1, argv=0x191df20) at main.c:220
```

FailedAssertion部分の変数値

```
(gdb) 
#3  0x0000000000651939 in tlist_matches_tupdesc (ps=0x19e69d0, tlist=0x19db648, varno=65002, tupdesc=0x19e78f8) at execScan.c:291
291                     Assert(var->varno == varno);
(gdb) p var->varno
$1 = 65001
(gdb) p varno
$2 = 65002
(gdb) p attrno
$3 = 1
```

**Comment by kaigai** [comment]
bbd61ee5f11884b72f46c04eef383e812245218e で修正。

これはGpuPreAggのクエリ書き換え時のミスですね。
元々のAggノードはOUTERスロットのデータを参照しますが、標準版のCustomScan Interfaceに対応する過程で、GpuPreAggノードはSCANスロットからデータを参照する必要がありました。

今までのようにVarノードを単純にcopyObjectするだけではNGで、GpuPreAggノードで実行されるexpression nodeはOUTER_VARをINDEX_VARに変換してやる必要があったのです。

```
typedef struct ExprContext
{
    NodeTag     type;

    /* Tuples that Var nodes in expression may refer to */
    TupleTableSlot *ecxt_scantuple;
    TupleTableSlot *ecxt_innertuple;
    TupleTableSlot *ecxt_outertuple;
       :
```
