### ISSUE TITLE
(JP) VACUUM ANALYZE中にSEGVが発生することがある

### ISSUE THREAD

**Issue by taiki-k** [pg-strom/devel#109]
PG-Stromの問題ではないかもしれませんが、VACUUM ANALYZEの実行中にSEGVが発生することがあります。
発生頻度は、3回に2回ぐらいかと思います。
PG-Stromありの方が、発生頻度が高いように思います。

* バックトレース
```
#0  0x0000000000469970 in nocachegetattr (tuple=0x2b292f8, attnum=9, tupleDesc=0x7ff4bad3a3d0) at heaptuple.c:486
#1  0x00000000005db712 in std_fetch_func (stats=0x2b1c198, rownum=2, isNull=0x7ffffc89c945 "") at analyze.c:1769
#2  0x00000000005dc541 in compute_scalar_stats (stats=0x2b1c198, fetchfunc=0x5db34f <std_fetch_func>, samplerows=30000,
    totalrows=6805444) at analyze.c:2315
#3  0x00000000005d8924 in do_analyze_rel (onerel=0x7ff4bad3faf8, vacstmt=0x2ac1220, acquirefunc=0x5d99b7 <acquire_sample_rows>,
    relpages=229029, inh=0 '\000', in_outer_xact=0 '\000', elevel=13) at analyze.c:531
#4  0x00000000005d7ffb in analyze_rel (relid=51466, vacstmt=0x2ac1220, in_outer_xact=0 '\000', bstrategy=0x2b12848) at analyze.c:269
#5  0x000000000065d5e9 in vacuum (vacstmt=0x2ac1220, relid=0, do_toast=1 '\001', bstrategy=0x2b12848, for_wraparound=0 '\000',
    isTopLevel=1 '\001') at vacuum.c:257
#6  0x0000000000802adc in standard_ProcessUtility (parsetree=0x2ac1220, queryString=0x2ac0828 "VACUUM ANALYZE;",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0x2ac15c8, completionTag=0x7ffffc89d1c0 "") at utility.c:643
#7  0x000000000080229f in ProcessUtility (parsetree=0x2ac1220, queryString=0x2ac0828 "VACUUM ANALYZE;",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0x2ac15c8, completionTag=0x7ffffc89d1c0 "") at utility.c:313
#8  0x00000000008011bd in PortalRunUtility (portal=0x2a69a28, utilityStmt=0x2ac1220, isTopLevel=1 '\001', dest=0x2ac15c8,
    completionTag=0x7ffffc89d1c0 "") at pquery.c:1187
#9  0x00000000008013bc in PortalRunMulti (portal=0x2a69a28, isTopLevel=1 '\001', dest=0x2ac15c8, altdest=0x2ac15c8,
    completionTag=0x7ffffc89d1c0 "") at pquery.c:1318
#10 0x000000000080083b in PortalRun (portal=0x2a69a28, count=9223372036854775807, isTopLevel=1 '\001', dest=0x2ac15c8,
    altdest=0x2ac15c8, completionTag=0x7ffffc89d1c0 "") at pquery.c:816
#11 0x00000000007f9f50 in exec_simple_query (query_string=0x2ac0828 "VACUUM ANALYZE;") at postgres.c:1045
#12 0x00000000007fe6a5 in PostgresMain (argc=1, argv=0x2a506c0, dbname=0x2a50528 "****", username=0x2a50508 "tkondo")
    at postgres.c:4012
#13 0x00000000007751bc in BackendRun (port=0x2a7c500) at postmaster.c:4130
#14 0x000000000077487d in BackendStartup (port=0x2a7c500) at postmaster.c:3805
#15 0x0000000000770c23 in ServerLoop () at postmaster.c:1573
#16 0x0000000000770253 in PostmasterMain (argc=3, argv=0x2a4f450) at postmaster.c:1220
#17 0x00000000006bf00e in main (argc=3, argv=0x2a4f450) at main.c:220
```

* 気になるログ

インデックスの作成中に表示されます。
```
DETAIL:  Process 19905 waits for AccessExclusiveLock on relation 60085 of database 35039.
ERROR:  index row requires 390876824 bytes, maximum size is 8191
ERROR:  index row requires 231558488 bytes, maximum size is 8191
ERROR:  index row requires 390925992 bytes, maximum size is 8191
```

**Comment by taiki-k** [comment]
一度、データベースを作成し直してみましたが、変わらずでした。
また、```VACUUM ANALYZE``` ではなく、 ```ANALYZE``` でも発生しました。
インデックスの作成中に上記のログが表示された後に ```ANALYZE``` を実行すると発生します。

**Comment by kaigai** [comment]
質問）
①PG-Strom無効化ではなく、shared_preload_librariesに何も指定せず、新規作成（initdb）したデータベースで同様の事象は発生しますか？

②ANALYZEするからには何かテーブルを作っているとは思いますが、テーブル作成・データINSERT時にはPG-Stromは有効ですか？
（ゴミデータの混入を心配している）

③真面目にコアダンプを追うと、以下のマクロでSEGVになっているけど、おかしい変数はどの人でしょうか。
（てか、ポインタ参照になるのは att か att[i] だけだよね？）
```
off = att_align_pointer(off, att[i]->attalign, -1,
                                            tp + off);
```

**Comment by taiki-k** [comment]
まず、②と③を回答します。
② テーブル作成時とINSERT時はPG-Strom有効です。
③ ポインタ参照は、```*(tp+off)``` もあります。どうも、これでSEGVになっているようです。
```att```と```att[i]``` (この時、i==9)は有効です。

```
(gdb) p off
$1 = 390876870
(gdb) p i
$2 = 9
(gdb) p att[9]->attalign
$3 = 105 'i'
(gdb) p tp
$4 = 0x18df2b8 "̡M"
(gdb) p *tp
$6 = -52 '\314'
(gdb) p tp+off
$8 = 0x18da417e <Address 0x18da417e out of bounds>
```

**Comment by kaigai** [comment]
offがこの値は明らかにおかしいね…

PostgreSQLのブロックサイズは 8KB だから、どんなに長いタプルでもこの範囲に入るハズ。
```
DETAIL:  Process 19905 waits for AccessExclusiveLock on relation 60085 of database 35039.
ERROR:  index row requires 390876824 bytes, maximum size is 8191
```
そしてこの値に近い…。

件のSEGVしているコードブロックは off=0 から初めて、順番にオフセットを増加させてるんだけれども、
そうすると、こんな変な値になるには
①att配列に何か変な値が入っている
②可変長データ(varlena)に変な値が入っている

外れの範囲から考えると ② の方が可能性は高そうですが。

そうすると、PG-Stromが何か変なデータを生成 → それを食って ANALYZE した人が食あたり

という可能性もありそうです。

だとすると、PG-Stromが全く絡んでいない状態での再現可能性は気になりますね。
varlenaデータを作る可能性があるのは、GpuHashJoin、およびGpuPreAggですので、データのINSERT元にこれらの処理が絡んでいるのかも。

**Comment by taiki-k** [comment]
データベースを作り直し、PG-Stromを読み込まない状態で試してみましたが、2回走行させた限り発生しません。

余談ですが、この問題、1/28の午前中くらいまでに直していただかないと…

**Comment by kaigai** [comment]
ああ、なるほど。アレのワークロードという事は、GpuHashJoinのProjectionコード臭いですね。

週末は手元に再現環境を持てないので、以下の情報を取ってもらえますか？
① att[] 配列の内容の出力
②(char *) tp から 1024 バイト分（たぶんこれ位で十分） のバイナリダンプ

コードから攻めてみます。

**Comment by taiki-k** [comment]
ちょっと、ここに貼るとまずいのものが出てきてますので、メールでお送りします。

**Comment by kaigai** [comment]
了解。遅くまでおつかれさまです。

**Comment by kaigai** [comment]
8d86e45e643c559312247b3b2b5f5d70736dddd4

アホみたいな原因でした…。Orz
