### ISSUE TITLE
(JP) 複数チャンクの結合を含む GpuSort で chunk_id_map の計算が合わない

### ISSUE THREAD

**Issue by kaigai** [pg-strom/devel#174]
バグなのだが、複数チャンクの結合はBGworkerを使わない方式に変えたい
（プロセス起動のオーバーヘッドが大きい＆性能メリット小さいため）ので、
そのタイミングで同時に修正する。
```
#0  0x00007f4fad552989 in raise () from /lib64/libc.so.6
#1  0x00007f4fad554098 in abort () from /lib64/libc.so.6
#2  0x0000000000917115 in ExceptionalCondition (
    conditionName=0x7f4fad0ae5c8 "!(gss->num_chunks == bms_num_members(gpusort->chunk_id_map))",
    errorType=0x7f4fad0ad71e "FailedAssertion", fileName=0x7f4fad0ad710 "src/gpusort.c", lineNumber=1657)
    at assert.c:54
#3  0x00007f4fad09d2fa in gpusort_task_complete (gtask=0x204500c60) at src/gpusort.c:1657
#4  0x00007f4fad07730e in check_completed_tasks (gts=0x1abc090) at src/cuda_control.c:1244
#5  0x00007f4fad077d1b in pgstrom_fetch_gputask (gts=0x1abc090) at src/cuda_control.c:1562
#6  0x00007f4fad078171 in pgstrom_exec_gputask (gts=0x1abc090) at src/cuda_control.c:1662
#7  0x00007f4fad09b3fa in gpusort_exec (node=0x1abc090) at src/gpusort.c:1005
#8  0x000000000067bc80 in ExecCustomScan (node=0x1abc090) at nodeCustom.c:113
#9  0x00000000006642b1 in ExecProcNode (node=0x1abc090) at execProcnode.c:462
#10 0x000000000066181b in ExecutePlan (estate=0x1abbf78, planstate=0x1abc090, operation=CMD_SELECT,
    sendTuples=1 '\001', numberTuples=0, direction=ForwardScanDirection, dest=0xdd99e0 <donothingDR>)
    at execMain.c:1549
```

**Comment by kaigai** [comment]
そもそもの実装方式を変えたのでクローズ。
