### ISSUE TITLE
(JP) Intel OpenCL CPU並列環境でSEGVすることがある

### ISSUE THREAD

**Issue by taiki-k** [pg-strom/devel#84]
Intel OpenCLのCPU並列環境でDBT-3のクエリーを実行すると、SEGVすることがあります。
バックトレースを見る限り、Intelドライバの情報しかないのですが、解決可能でしょうか？

* Core原因のメッセージ
```
Core was generated by `postgres: bgworker: PG-Strom OpenCL Server             '.
Program terminated with signal 11, Segmentation fault.
```

* バックトレース
```
#0  0x00007fb4edcb5732 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#1  0x00007fb4ed1b309d in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#2  0x00007fb4ed1b3f60 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#3  0x00007fb4ed1a45a4 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#4  0x00007fb4ed1add75 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#5  0x00007fb4ed1ae4d8 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#6  0x00007fb4edcac5d8 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#7  0x00007fb4edcac6b9 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#8  0x00007fb4edcac8bb in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#9  0x00007fb4ed184f89 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#10 0x00007fb4edcac5d8 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#11 0x00007fb4edcac6b9 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#12 0x00007fb4edcac8bb in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#13 0x00007fb4ed1825b9 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#14 0x00007fb4edcac2af in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#15 0x00007fb4edcad0d9 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#16 0x00007fb4ed1311a8 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#17 0x00007fb4ed105efc in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#18 0x00007fb4ed1190c7 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#19 0x00007fb4ed1005d3 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libOclCpuBackEnd.so
#20 0x00007fb4eebe5f57 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libcpu_device.so
#21 0x00007fb4ef608015 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libintelocl.so
#22 0x00007fb4ef0dd837 in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libtask_executor.so
#23 0x00007fb4ef0ddc0e in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libtask_executor.so
#24 0x00007fb4ef0f4e8d in ?? () from /opt/intel/opencl-1.2-4.5.0.8/lib64/libtask_executor.so
#25 0x00007fb4eef9ffea in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7fb3fbf27e80,
    parent=..., child=0xd007282) at ../../src/tbb/custom_scheduler.h:474
#26 0x00007fb4eef9bf39 in tbb::internal::arena::process (this=0x0, s=...) at ../../src/tbb/arena.cpp:94
#27 0x00007fb4eef9a416 in tbb::internal::market::process (this=0x0, j=...) at ../../src/tbb/market.cpp:473
#28 0x00007fb4eef96410 in tbb::internal::rml::private_worker::run (this=0x0) at ../../src/tbb/private_server.cpp:273
#29 0x00007fb4eef963b6 in tbb::internal::rml::private_worker::thread_routine (arg=0x0) at ../../src/tbb/private_server.cpp:226
#30 0x0000003906c079d1 in start_thread () from /lib64/libpthread.so.0
#31 0x00000039068e8b6d in clone () from /lib64/libc.so.6
```

* 対象のSQL
```sql
EXPLAIN ANALYZE
select
 sum(l_extendedprice * l_discount) as revenue
from
 lineitem
where
 l_shipdate >= date '1993-01-01' and
 l_shipdate < date '1993-01-01' + interval '1 year' and
 l_discount between 0.08 - 0.01 and 0.08 + 0.01 and
 l_quantity < 25;
```

* 手動実行時のメッセージ
```
INFO:  Agg cost = 5491488.89..5491488.90 nrows (4097666 => 9)
ERROR:  message queue wait timeout
Time: 60729.925 ms
```
このメッセージが表示されて、しばらくするとクラッシュします。

**Comment by kaigai** [comment]
Intel環境は対応しない事にします。
